sites:
  - name: kognise
    url: https://kognise.dev/
    colors:
      border: '#ced4da'
      text: '#000000'
      links: '#6741d9'
    stylesheets:
      - https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&display=swap
    font_stack: '"IBM Plex Mono", monospace'
  - name: sugarfi
    url: https://sugarfi.dev/
    stylesheets:
      - https://sugarfi.dev/fonts.css
    font_stack: '"Free Pixel"'
  - name: arcade
    url: https://arcade.srht.site
    colors:
      border: '#268bd2'
      text: '#002b36'
      links: '#d33682'
    font_stack: 'serif'

default_colors:
  border: '#000000'
  text: '#000000'
  links: '#0000ee'
