sites:
  - name: kognise
    url: https://kognise.dev/
    colors:
      border: '#ced4da'
      text: '#000000'
      links: '#6741d9'
    stylesheets:
      - https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400&display=swap
    font_stack: '"IBM Plex Mono", monospace'
  - name: sugarfi
    url: https://sugarfi.dev/
    stylesheets:
      - https://sugarfi.dev/fonts.css
    font_stack: '"Free Pixel"'
  - name: arcade
    url: https://raleighwi.se
    colors:
      border: '#268bd2'
      text: '#002b36'
      links: '#d33682'
    font_stack: serif
  - name: piero
    url: https://piemadd.com/
    colors:
      border: '#131517'
      text: '#ffffff'
      links: '#468af0'
    stylesheets:
      - https://fonts.googleapis.com/css?family=Montserrat&display=swap
    font_stack: '"Montserrat", sans-serif' 
  - name: roylatgnail
    url: https://estrogens.rocks/
    font_stack: sans-serif
  - name: celeste
    url: https://celeste.exposed/
    stylesheets: 
      - https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap
      - https://celeste.exposed/embed.css
    font_stack: '"Libre Baskerville", serif'
  - name: skylar bleed
    url: https://murder.rocks/~skye/README.html
    font_size: 16px
  - name: ishan
    url: https://ishan.is-a.dev/
    colors:
      border: '#c9b697'
      text: '#000000'
      links: '#4d96c6'
    stylesheets:
      - https://fonts.googleapis.com/css?family=Nunito&display=swap
    font_stack: Futura, Nunito, Verdana, sans-serif 
  - name: perrypal
    url: https://perrypal.xyz/
    colors:
      border: 'transparent'
      text: '#ffffff'
      links: '#275a90'
    stylesheets:
      - https://fonts.googleapis.com/css?family=Quicksand&display=swap
    font_stack: Quicksand
  - name: hypnotic
    url: https://hypnoticsiege.net/
    colors:
      border: '#393e46'
      text: '#ffffff'
      links: '#3fa3eb'

default_colors:
  border: '#000000'
  text: '#000000'
  links: '#0000ee'
